#!/bin/bash      

if [ "$1" = "YES" ]
then
    defaults write com.apple.finder AppleShowAllFiles YES
    killall Finder
elif [ "$1" = "NO" ]
then
    defaults write com.apple.finder AppleShowAllFiles NO
    killall Finder
fi

